/* Generated by Yosys 0.19+42 (git sha1 7d4f87d69f0, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_rc(clk, ori, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input ori;
  wire ori;
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(_04_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(_04_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _12_ (
    .A(_04_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(count[1]),
    .Q(count[0]),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(count[2]),
    .Q(count[1]),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clk),
    .D(count[3]),
    .Q(count[2]),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__dfstp_2 _16_ (
    .CLK(clk),
    .D(count[0]),
    .Q(count[3]),
    .SET_B(_08_)
  );
  assign _04_ = ori;
  assign _05_ = _00_;
  assign _06_ = _01_;
  assign _07_ = _02_;
  assign _08_ = _03_;
endmodule
